[package]
name = "br"
version = "0.7.0"
authors = ["programingjd"]
edition = "2021"

[lib]
crate-type = ["cdylib","rlib"]

[dependencies.wasm-bindgen]
version = "0.2"

[dependencies.brotli]
#version = "3.4"
git = "https://github.com/programingjd/rust-brotli.git"
features=["std","disable-timer","simd"]
default-features=false

[profile.release]
opt-level = "s"
lto = true
#panic = "abort"
